### ISSUE TITLE
Type inference wrong for strings prefixed with `+` and `0`

### ISSUE THREAD

**Issue by elliottinvent** [NUMtechnology/compactdata-python#1]
It is interpreting `+1` as numeric `1`:
```
print(compactdata.loads("a=+1"))
->  {'a': 1}
```

And `01` as numeric `1`:
```
print(compactdata.loads("a=01"))
->  {'a': 1}
```

These are invalid numeric JSON values. CompactData type inference should result in these being strings, like so:

```
print(compactdata.loads("a=+1"))
->  {'a': '+1'}
print(compactdata.loads("a=01"))
->  {'a': '01'}
```

**Comment by gustasthegreat** [comment]
Fixed in https://github.com/NUMtechnology/compactdata-python/commit/f536f3bbc54e353118a96f622cc0ea57e3743ca7.
