### ISSUE TITLE
Unexpected results when using escapes

### ISSUE THREAD

**Issue by elliottinvent** [NUMtechnology/compactdata-python#2]
**Example using backslash escape:**
```
a=\(
-> {'a': '\\('}
```

Expected:
`{'a': '('}`

**Example using tilde escape:**
```
a=~( 
-> {'a': '~('}
```

Expected:

 - `error` if tilde not set as escape char, since `(` should be reserved; or 
 - if tilde used as escape char, then: `{'a': '('}`

**Comment by gustasthegreat** [comment]
Fixed in https://github.com/NUMtechnology/compactdata-python/commit/f536f3bbc54e353118a96f622cc0ea57e3743ca7.
